theme: jekyll-theme-minimal
title: Dynamic Bayesian Network Outlier Detection (DBNOD)
description: A complete multivariate time series outlier detection system ranging from pre-processing to score-analysis.

#logo: [Location of the logo]
show_downloads: "true"
google_analytics: UA-127454922-1
